const text = (name, label, options = {}) => ({
  name,
  label,
  type: "text",
  required: options.required ?? true,
  placeholder: options.placeholder ?? "",
  help: options.help ?? "",
});

const number = (name, label, options = {}) => ({
  name,
  label,
  type: "number",
  required: options.required ?? true,
  min: options.min,
  max: options.max,
  placeholder: options.placeholder ?? "",
  help: options.help ?? "",
});

const aircraftColumns = [
  "MakeModel", "Registration", "Owner", "Location", "LocationName",
  "Home", "RentalDry", "RentalWet", "SalePrice",
];

const aircraftConfigColumns = [
  "MakeModel", "Crew", "Seats", "CruiseSpeed", "GPH",
  "FuelType", "MTOW", "EmptyWeight", "Price",
];

const jobColumns = [
  "FromIcao", "ToIcao", "Amount", "Type", "Commodity", "Pay", "Expires",
];

const flightLogColumns = [
  "MakeModel", "Registration", "From", "To", "FlightTime",
  "Distance", "FuelUsed", "Income",
];

const paymentColumns = [
  "Date", "To", "From", "Amount", "Reason", "Comment",
];

const commodityColumns = [
  "Location", "Commodity", "Amount", "Weight", "Volume"
];

const queries = [
  {
    id: "aircraft-status-registration",
    category: "Aircraft",
    label: "Aircraft Status By Registration",
    description: "Looks up aircraft status using an aircraft registration number.",
    query: "aircraft",
    search: "status",
    essentialColumns: aircraftColumns,
    fields: [text("aircraftreg", "Aircraft Registration")],
  },
  {
    id: "aircraft-configs",
    category: "Aircraft",
    label: "Aircraft Configs",
    description: "Returns aircraft configuration data.",
    query: "aircraft",
    search: "configs",
    essentialColumns: aircraftConfigColumns,
    fields: [],
  },
  {
    id: "aircraft-aliases",
    category: "Aircraft",
    label: "Aircraft Aliases",
    description: "Returns aircraft aliases.",
    query: "aircraft",
    search: "aliases",
    fields: [],
  },
  {
    id: "aircraft-for-sale",
    category: "Aircraft",
    label: "Aircraft For Sale",
    description: "Lists aircraft currently offered for sale.",
    query: "aircraft",
    search: "forsale",
    essentialColumns: aircraftColumns,
    fields: [],
  },
  {
    id: "aircraft-by-makemodel",
    category: "Aircraft",
    label: "Aircraft By Make/Model",
    description: "Searches aircraft by exact make/model value.",
    query: "aircraft",
    search: "makemodel",
    essentialColumns: aircraftColumns,
    fields: [text("makemodel", "Aircraft Make/Model", { placeholder: "e.g. Cessna 172 Skyhawk" })],
  },
  {
    id: "aircraft-by-owner",
    category: "Aircraft",
    label: "Aircraft By Owner Name",
    description: "Searches aircraft by owner name.",
    query: "aircraft",
    search: "ownername",
    essentialColumns: aircraftColumns,
    fields: [text("ownername", "Aircraft Owner Name")],
  },
  {
    id: "aircraft-by-registration",
    category: "Aircraft",
    label: "Aircraft By Registration",
    description: "Searches aircraft by registration.",
    query: "aircraft",
    search: "registration",
    essentialColumns: aircraftColumns,
    fields: [text("aircraftreg", "Aircraft Registration")],
  },
  {
    id: "aircraft-by-id",
    category: "Aircraft",
    label: "Aircraft By ID",
    description: "Searches aircraft by serial number / aircraft ID.",
    query: "aircraft",
    search: "serialnumber",
    essentialColumns: aircraftColumns,
    fields: [text("serialnumber", "Aircraft ID / Serial Number")],
  },
  {
    id: "aircraft-by-key",
    category: "Aircraft",
    label: "Aircraft By Key",
    description: "Returns aircraft associated with your read access key.",
    query: "aircraft",
    search: "key",
    needsReadAccessKey: true,
    essentialColumns: aircraftColumns,
    fields: [],
  },
  {
    id: "assignments-by-key",
    category: "Account / Group",
    label: "Assignments By Key",
    description: "Returns assignments associated with your read access key.",
    query: "assignments",
    search: "key",
    needsReadAccessKey: true,
    essentialColumns: jobColumns,
    fields: [],
  },
  {
    id: "smart-job-matcher",
    category: "Smart Tools",
    label: "Smart Job Matcher",
    description: "Finds jobs for a specific commodity from your hubs that fit a specific rentable aircraft.",
    query: "matcher", // special identifier for the UI to hit the matcher endpoint
    search: "custom",
    fields: [
      text("icaos", "Hubs (ICAOs)", { placeholder: "e.g. SBGR-SBSP-SBKP", help: "Separados por hífen." }),
      text("commodity", "Commodity", { placeholder: "e.g. VIP" }),
      text("makemodel", "Aircraft Make/Model", { placeholder: "e.g. Embraer Phenom 100" })
    ],
  },
  {
    id: "commodities-by-key",
    category: "Account / Group",
    label: "Commodities By Key",
    description: "Returns commodities associated with your read access key.",
    query: "commodities",
    search: "key",
    needsReadAccessKey: true,
    essentialColumns: commodityColumns,
    fields: [],
  },
  {
    id: "facilities-by-key",
    category: "Account / Group",
    label: "Facilities By Key",
    description: "Returns facilities associated with your read access key.",
    query: "Facilities",
    search: "key",
    needsReadAccessKey: true,
    fields: [],
  },
  {
    id: "fbos-by-key",
    category: "FBO",
    label: "FBOs By Key",
    description: "Returns FBOs associated with your read access key.",
    query: "fbos",
    search: "key",
    needsReadAccessKey: true,
    fields: [],
  },
  {
    id: "fbos-for-sale",
    category: "FBO",
    label: "FBOs For Sale",
    description: "Lists FBOs offered for sale.",
    query: "fbos",
    search: "forsale",
    fields: [],
  },
  {
    id: "fbo-monthly-summary",
    category: "FBO",
    label: "FBO Monthly Summary by ICAO",
    description: "Returns an FBO monthly summary for an ICAO, month and year.",
    query: "fbos",
    search: "monthlysummary",
    needsReadAccessKey: true,
    fields: [
      number("month", "Month", { min: 1, max: 12 }),
      number("year", "Year", { min: 2000, max: 2100 }),
      text("icao", "ICAO", { placeholder: "e.g. CZFA" }),
    ],
  },
  {
    id: "flightlogs-key-monthyear",
    category: "Flight Logs",
    label: "Flight Logs By Key / Month / Year",
    description: "Returns flight logs for your read access key in a month/year.",
    query: "flightlogs",
    search: "monthyear",
    needsReadAccessKey: true,
    essentialColumns: flightLogColumns,
    fields: [
      number("month", "Month", { min: 1, max: 12 }),
      number("year", "Year", { min: 2000, max: 2100 }),
    ],
  },
  {
    id: "flightlogs-reg-monthyear",
    category: "Flight Logs",
    label: "Flight Logs By Registration / Month / Year",
    description: "Returns flight logs for an aircraft registration in a month/year.",
    query: "flightlogs",
    search: "monthyear",
    essentialColumns: flightLogColumns,
    fields: [
      text("aircraftreg", "Aircraft Registration"),
      number("month", "Month", { min: 1, max: 12 }),
      number("year", "Year", { min: 2000, max: 2100 }),
    ],
  },
  {
    id: "flightlogs-serial-monthyear",
    category: "Flight Logs",
    label: "Flight Logs By Serial Number / Month / Year",
    description: "Returns flight logs for an aircraft serial number in a month/year.",
    query: "flightlogs",
    search: "monthyear",
    essentialColumns: flightLogColumns,
    fields: [
      text("serialnumber", "Aircraft ID / Serial Number"),
      number("month", "Month", { min: 1, max: 12 }),
      number("year", "Year", { min: 2000, max: 2100 }),
    ],
  },
  {
    id: "flightlogs-key-fromid",
    category: "Flight Logs",
    label: "Flight Logs By Key From ID (Limit 500)",
    description: "Returns up to 500 flight log records from an ID for your read access key.",
    query: "flightlogs",
    search: "id",
    needsReadAccessKey: true,
    essentialColumns: flightLogColumns,
    fields: [text("fromid", "From ID")],
  },
  {
    id: "flightlogs-groupaircraft-fromid",
    category: "Flight Logs",
    label: "Flight Logs By Key From ID — All Group Aircraft (Limit 500)",
    description: "Returns up to 500 group-aircraft flight logs from an ID.",
    query: "flightlogs",
    search: "id",
    needsReadAccessKey: true,
    fixedParams: { type: "groupaircraft" },
    essentialColumns: flightLogColumns,
    fields: [text("fromid", "From ID")],
  },
  {
    id: "flightlogs-reg-fromid",
    category: "Flight Logs",
    label: "Flight Logs By Registration From ID (Limit 500)",
    description: "Returns up to 500 flight logs for a registration from an ID.",
    query: "flightlogs",
    search: "id",
    essentialColumns: flightLogColumns,
    fields: [text("aircraftreg", "Aircraft Registration"), text("fromid", "From ID")],
  },
  {
    id: "flightlogs-serial-fromid",
    category: "Flight Logs",
    label: "Flight Logs By Serial Number From ID (Limit 500)",
    description: "Returns up to 500 flight logs for a serial number from an ID.",
    query: "flightlogs",
    search: "id",
    essentialColumns: flightLogColumns,
    fields: [text("serialnumber", "Aircraft ID / Serial Number"), text("fromid", "From ID")],
  },
  {
    id: "group-members",
    category: "Account / Group",
    label: "Group Members",
    description: "Returns group members for your read access key.",
    query: "group",
    search: "members",
    needsReadAccessKey: true,
    fields: [],
  },
  {
    id: "icao-aircraft",
    category: "ICAO",
    label: "ICAO Listing of Aircraft",
    description: "Lists aircraft at an ICAO.",
    query: "icao",
    search: "aircraft",
    essentialColumns: aircraftColumns,
    fields: [text("icao", "ICAO")],
  },
  {
    id: "icao-fbos",
    category: "ICAO",
    label: "ICAO Listing of FBOs",
    description: "Lists FBOs at an ICAO.",
    query: "icao",
    search: "fbo",
    fields: [text("icao", "ICAO")],
  },
  {
    id: "icao-jobs-to",
    category: "ICAO",
    label: "ICAO Jobs To",
    description: "Returns jobs whose destination matches one or more ICAOs.",
    query: "icao",
    search: "jobsto",
    essentialColumns: jobColumns,
    fields: [
      text("icaos", "ICAOs", {
        placeholder: "e.g. CZFA-CEX4-CYMA",
        help: "Use the same multi-ICAO format accepted by the FSEconomy endpoint.",
      }),
    ],
  },
  {
    id: "icao-jobs-from",
    category: "ICAO",
    label: "ICAO Jobs From",
    description: "Returns jobs whose origin matches one or more ICAOs.",
    query: "icao",
    search: "jobsfrom",
    essentialColumns: jobColumns,
    fields: [
      text("icaos", "ICAOs", {
        placeholder: "e.g. CZFA-CEX4-CYMA",
        help: "Use the same multi-ICAO format accepted by the FSEconomy endpoint.",
      }),
    ],
  },
  {
    id: "payments-monthyear",
    category: "Payments",
    label: "Payments By Month / Year",
    description: "Returns payments for your read access key in a month/year.",
    query: "payments",
    search: "monthyear",
    needsReadAccessKey: true,
    essentialColumns: paymentColumns,
    fields: [
      number("month", "Month", { min: 1, max: 12 }),
      number("year", "Year", { min: 2000, max: 2100 }),
    ],
  },
  {
    id: "payments-fromid",
    category: "Payments",
    label: "Payments From ID (Limit 500)",
    description: "Returns up to 500 payments from an ID.",
    query: "payments",
    search: "id",
    needsReadAccessKey: true,
    essentialColumns: paymentColumns,
    fields: [text("fromid", "From ID")],
  },
  {
    id: "payments-archive-monthyear",
    category: "Payments",
    label: "Archive — Payments By Month / Year",
    description: "Returns archived payments for your read access key in a month/year.",
    query: "payments",
    search: "monthyear",
    needsReadAccessKey: true,
    flagParams: ["archive"],
    essentialColumns: paymentColumns,
    fields: [
      number("month", "Month", { min: 1, max: 12 }),
      number("year", "Year", { min: 2000, max: 2100 }),
    ],
  },
  {
    id: "payments-archive-fromid",
    category: "Payments",
    label: "Archive — Payments From ID (Limit 500)",
    description: "Returns up to 500 archived payments from an ID.",
    query: "payments",
    search: "id",
    needsReadAccessKey: true,
    flagParams: ["archive"],
    essentialColumns: paymentColumns,
    fields: [text("fromid", "From ID")],
  },
  {
    id: "statistics-by-key",
    category: "Account / Group",
    label: "Statistics By Key",
    description: "Returns statistics associated with your read access key.",
    query: "statistics",
    search: "key",
    needsReadAccessKey: true,
    fields: [],
  },
];

function publicQueryDefinition(query) {
  return {
    id: query.id,
    category: query.category,
    label: query.label,
    description: query.description,
    fields: query.fields,
    needsReadAccessKey: Boolean(query.needsReadAccessKey),
    essentialColumns: query.essentialColumns || [],
  };
}

module.exports = {
  queries,
  publicQueryDefinition,
};
